/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package atcoder_kotlin

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    val list = listOf(1, 2, 3, 4, 5)
    list.map{it * 2}.forEach{println(it)}
}
