name: Notify Solve Streak

on:
  push:
    paths:
      - '**/*'  # すべてのファイルが対象

jobs:
  notify-solve-streak:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - name: Has diff?
      if: github.event.before == '0000000000000000000000000000000000000000'
      run: |
        echo "This is the first commit, skipping diff."
        exit 0

    - name: Get changed files
      run: |
        files=$(git diff --name-only --diff-filter=A ${{ github.event.before }} ${{ github.sha }}  | grep -E '^[0-9]+-[A-G]')
        if [ -n "$files" ]; then
          echo "Found file(s): $files"
          curl -X POST -F content="$files" "<change your hooks url>" &> /dev/null
        else
          echo "No matching files found."
          exit 0
        fi    